// This file is auto-generated by @hey-api/openapi-ts

export const $User = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      example: 'b3f271ef-e73b-4c12-ad85-665c3686017a',
    },
    name: {
      type: 'string',
      example: 'Gandalf the Grey',
    },
    email: {
      type: 'string',
      example: 'gandalf.the.grey@test.com',
    },
    profileImage: {
      type: 'string',
      example: 'http://localhost:3000/static/gandalf.png',
    },
  },
} as const;

export const $SME = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      example: '6fa0ea41-9249-43d5-8479-81af6a55b946',
    },
    legalName: {
      type: 'string',
      example: 'Fellowship GmbH',
    },
    businessType: {
      type: 'string',
      example: 'GMBH',
      enum: ['GMBH', 'EINZELUNTERNEHMEN'],
    },
  },
} as const;

export const $Transaction = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      example: '59beb78c-4227-42d1-a1b5-9a8405ff3416',
    },
    smeId: {
      type: 'string',
      example: '5fb473af-2413-43ee-b899-7a4835ee607f',
    },
    amount: {
      type: 'string',
      example: '-98.11',
    },
    status: {
      type: 'string',
      example: 'COMPLETED',
      enum: ['REJECTED', 'PENDING', 'COMPLETED', 'REVERSED'],
    },
    userId: {
      type: 'string',
      example: '58c0645c-ce36-4395-9658-9a654cd3f3f9',
    },
    transactionTime: {
      type: 'string',
      example: '2022-10-16T19:07:48.626Z',
    },
    merchantIconUrl: {
      type: 'string',
      example: 'http://localhost:3200/static/mi-lieferando.png',
    },
    merchantName: {
      type: 'string',
      example: 'Lieferando',
    },
    currency: {
      type: 'string',
      example: 'EUR',
      enum: ['USD', 'EUR'],
    },
    rejectionReason: {
      type: 'string',
      nullable: true,
      example: null,
      enum: [
        'NOT_PERMITTED',
        'INSUFFICIENT_FUNDS',
        'CARD_MONTHLY_LIMIT_REACHED',
        'CARD_DAILY_LIMIT_REACHED',
        'CARD_EXPIRED',
        'CARD_SUSPENDED',
        'CARD_NOT_ACTIVE',
        'INCORRECT_PIN',
      ],
    },
  },
} as const;

export const $BadRequest = {
  type: 'object',
  properties: {
    error: {
      type: 'string',
      example: 'Bad Request',
    },
    message: {
      type: 'string',
    },
  },
} as const;

export const $UnauthorizedError = {
  type: 'object',
  properties: {
    error: {
      type: 'string',
      example: 'Unauthorized',
    },
    message: {
      type: 'string',
      example: 'Incorrect login or password',
    },
  },
} as const;
